version: "3"
services:
  postgresql:
    image: postgres:12.2
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=bl1nkker
    mem_limit: 36g

  app:
    image: blinkker/strapi-hi-tech:0.0.1-amd
    ports:
      - "1337:1337"
    environment:
      - DATABASE_HOST=postgresql
      - DATABASE_PORT=5432
      - DATABASE_NAME=hi_tech
      - DATABASE_USERNAME=postres
      - DATABASE_PASSWORD=bl1nkker

volumes:
  postgres-data:
